# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyMessengerRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyMessengerRN

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'

end
