# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyMessengerRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyMessengerRN

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Database', '~> 5.9.0'

  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  #pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

end
